### ISSUE TITLE
Life Cycle Analysis for Bill of Materials V1

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-frog-sensor#11]
We should do a somewhat good life cycle analysis of the materials used to construct the sensor. This should help answer questions like: What should the enclosure be made of? What is the impact of deploying X number of sensors. etc.

**Comment by kevinjmiller2** [comment]
@keenanjohnson, some initial thoughts [here](https://docs.google.com/document/d/1PLEBLrZIj_m_csX-auDr22nOP_rRxhiYsVmOVrjhuzY/edit?usp=sharing) regarding lifecycle emissions per sensor. It's a very rough estimate of things, but I think it'll be a good start. Two areas where I could use some input:

1. I need to dig into the cloud part in more detail but point me toward any resources you have to help me understand how much cloud compute power you're likely using per sensor.
2. Do you have data for weight of the full system? This will be helpful for a rough scope 3 emissions estimate.

**Comment by keenanjohnson** [comment]
@kevinjmiller2 ! This is incredible work! I'll review this today, but thank you so much!

1. I believe there are some good calculators from places like Microsoft for cloud compute, but we can look into that. 
2. I can get you a rough weight estimate yeah. I should add that to the BOM!

**Comment by keenanjohnson** [comment]
[I added a mass column to the BOM @kevinjmiller2!](https://docs.google.com/spreadsheets/d/1lsWCXFawsJNGc44bqFXWkpjHfIFZQEj5UceJV4AiuK0/edit#gid=0)

![image](https://user-images.githubusercontent.com/2559382/127571393-2806fb03-2438-4a2e-823d-02f84ed16b28.png)

Total mass is around 346 grams.

**Comment by keenanjohnson** [comment]
In #4 I measured the power consumption of the sensor to be 2.6 Watts on average.

**Comment by keenanjohnson** [comment]
@all-contributors please add @kevinjmiller2 for his great ideas and content

**Comment by keenanjohnson** [comment]
I think this was an excellent first draft of an analysis for the Frog V1. We'll open another issue to complete a similar and hopefully more in depth analysis for the Frog V2 Sensor.
