### ISSUE TITLE
Update BOM for Frog Sensor Version 3

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-frog-sensor#133]

**Comment by keenanjohnson** [comment]
https://github.com/Ribbit-Network/ribbit-network-frog-sensor/pull/137

**Comment by keenanjohnson** [comment]
@pascaljoly I've updated the BOM for the V3 Frog Here. This is still a bit of a draft, but give it a review and I think it should have everything you need.

**Comment by pascaljoly** [comment]
@keenanjohnson I did not see the BOM in your message. do you have a link for it?
thanks,
Pascal

**Comment by keenanjohnson** [comment]
Oh it was in the PR I linked above: https://github.com/Ribbit-Network/ribbit-network-frog-sensor/pull/137, but you can also find it in the new V3 branch: https://github.com/Ribbit-Network/ribbit-network-frog-sensor/blob/frog_v3/hardware/v3/ribbit_network_frog_sensor_bom.csv

**Comment by pascaljoly** [comment]
thanks. I trust you these are the correct parts. Is there a way to group
them in one public "shopping cart" link with adafruit?

**Comment by keenanjohnson** [comment]
Merged #137 with the updated BOM

**Comment by keenanjohnson** [comment]
I'm not sure if there is a way to do that @pascaljoly! That would be a great improvement if so possibly!
