### ISSUE TITLE
Add a Barometer to the Sensor

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-frog-sensor#15]
According to the [Interface Description for the SCD30](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/9.5_CO2/Sensirion_CO2_Sensors_SCD30_Interface_Description.pdf), the sensor can provide a higher accuracy CO2 PPM when a barometric pressure measurment is provided.

A suitable barometer should be picked out for the system and trialed to see if the accuracy improves.

See section 1.4.8 of the interface description, also attached here:
![image](https://user-images.githubusercontent.com/2559382/128070675-b68931bb-0894-4e2b-895b-ba776dbcc83c.png)

[Sensirion_CO2_Sensors_SCD30_Interface_Description.pdf](https://github.com/Ribbit-Network/ribbit-network-sensor/files/6926454/Sensirion_CO2_Sensors_SCD30_Interface_Description.pdf)

**Comment by keenanjohnson** [comment]
I've just purchased a few of these simple barometeric pressure sensors and will test when they arrive.

https://www.adafruit.com/product/4494

**Comment by keenanjohnson** [comment]
The barometer has arrived. I'm going to install for testing shortly.

![E8J7LJ6VEAUZ_Il](https://user-images.githubusercontent.com/2559382/128585554-248443f6-3b08-490a-9ea7-85eb99249fa8.jpeg)

**Comment by lwbantoto** [comment]
Awesome! How are you planning to test the barometer?

**Comment by keenanjohnson** [comment]
Right now I’m planning on taking two sensors right next to each other and
comparing the barometer compensated sensor to the non compensated one.

Hopefully there will be a sufficient noise reduction or shift in the
compensated sensor!

**Comment by keenanjohnson** [comment]
I've wired the sensor and integrated in software:
https://github.com/Ribbit-Network/ribbit-network-frog-sensor/blob/912850c6732eaf6c82549f14c60ef1ddb7b91eb2/software/co2/co2.py#L101-L102

I don't see a noticeable difference in the noise of the sensor based on my testing, however, I think this will make a big difference for sensors that exist at different altitudes. I'm making the call to include it in the sensor :)
