### ISSUE TITLE
SparkFun Qwiic or Stemma QT SHIM suggested link out of stock

### ISSUE THREAD

**Issue by akhilgupta1093** [Ribbit-Network/ribbit-network-frog-sensor#150]
This [old link](https://www.adafruit.com/product/4463) is out of stock. I got it [here](https://www.amazon.com/SparkFun-Raspberry-Friction-Based-Connector-Soldering/dp/B082J2QYF3/ref=sr_1_1?crid=3FXRZ2WMSC8GN&keywords=SparkFun+Qwiic+or+Stemma+QT+SHIM+for+Raspberry+Pi+%2F+SBC&qid=1662919633&sprefix=sparkfun+qwiic+or+stemma+qt+shim+for+raspberry+pi+%2F+sbc%2Caps%2C179&sr=8-1) on amazon.

**Comment by keenanjohnson** [comment]
Thanks for bringing this up @akhilgupta1093 ! Want to take a shot at opening a PR to correct the BOM?

**Comment by keenanjohnson** [comment]
The old link is back in stock, so I'm closing this out.
