### ISSUE TITLE
Broken links to international BOMs

### ISSUE THREAD

**Issue by spoogle** [Ribbit-Network/ribbit-network-frog-sensor#154]
The references to the international BOMs are broken.

On this page, there is a broken reference to a folder of localised BOMs:

https://github.com/Ribbit-Network/ribbit-network-frog-sensor/tree/main/hardware/v2

> We also have an on-going effort to create different versions of the Bill of Materials that are localized to different regions. See the Folder here https://github.com/Ribbit-Network/ribbit-network-frog-sensor/blob/main/hardware/v2/international_boms for our current list. We welcome any new contributions!

Elsewhere, there is a reference to https://github.com/Ribbit-Network/ribbit-network-frog-sensor/blob/main/hardware/v2/hardware/international_boms/ribbit_network_frog_sensor_bom_uk.csv  Sorry, I can't find the reference now!

**Comment by eaudiffred** [comment]
@spoogle, thanks for pointing out the broken link.  I just submitted a PR with the link corrections.  The international BOMs are currently contained in the V1 folder and have only been created for V1.  There are a lot of similarities between V1 and V3, but we still have yet to create any international BOMs for V3.  Any input you have for creating an international BOM for V3 is welcome!

**Comment by keenanjohnson** [comment]
Thanks @eaudiffred !

**Comment by eaudiffred** [comment]
Submitted PR #176 which adds a folder to store any international BOMS
