### ISSUE TITLE
Design Better Sensor Bracket

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-frog-sensor#16]
The current sensor bracket is only half of what's needed. It's approximately the correct size and the clip on the top works well, but there are not attachment points for the physical hardware.

[Current Hardware .stl file](https://github.com/Ribbit-Network/ribbit-network-sensor/blob/main/hardware/frog_sensor_bracket.stl)
[Current Hardware OnShape Design](https://cad.onshape.com/documents/68cff890348370ef6e764cea/w/7efc22ac1ba4a88deb843b28/e/5135282a39b15ccbb0e55202)

![image](https://user-images.githubusercontent.com/2559382/128103765-1678acb8-f94e-4be6-99ac-a10f603e68fc.png)
![image](https://user-images.githubusercontent.com/2559382/128103775-9da59770-42c5-4a5e-8e1b-b1a72a514dbf.png)

**Comment by keenanjohnson** [comment]
I think the easiest thing would be to create some holes in the bracket and then attach the boards with some brass standoffs like this: 
![image](https://user-images.githubusercontent.com/2559382/128103950-d05f797c-540b-47be-80ef-e162b8295df4.png)

**Comment by eaudiffred** [comment]
Looking for help on this one still?

I like the standoff idea.  What are the board dimensions?  I can add the holes in the bracket.

Are you set on the current layout?  Depending on the hole dimensions, you can also stack the boards using these same brass spacers.  I guess overall space in the housing would come into play then too.  

The small square board and the sensor look kind of tricky to mount.  I'd have to think about that.  

This STL file just has holes for 2.5mm threaded standoffs.  
![image](https://user-images.githubusercontent.com/88562047/128575363-6b87a2e3-cc29-4277-bdbf-309dbb488065.png)
![image](https://user-images.githubusercontent.com/88562047/128575388-d0c7b359-967a-4da1-b412-b5c32037b1ae.png)
![image](https://user-images.githubusercontent.com/88562047/128575577-d95111e1-da95-43ed-903e-55b856633197.png)

[Sensor Clip v1.zip](https://github.com/Ribbit-Network/ribbit-network-sensor/files/6948117/Sensor.Clip.v1.zip)

**Comment by keenanjohnson** [comment]
Yeah, possibly there is just a better design for this bracket altogether :). I can get you some dimensions shortly!

Thanks for helping!

**Comment by keenanjohnson** [comment]
Here are some dimensions. I believe all the boards have holes for M2.5 bolts.

* [Raspberry Pi Zero](https://www.raspberrypi.org/documentation/hardware/raspberrypi/mechanical/rpi_MECH_Zero_1p3.pdf)
![image](https://user-images.githubusercontent.com/2559382/128624004-e4d92ea6-689c-4f8e-8817-9b7d88727dec.png)
* [Co2 Sensor](https://cdn.sparkfun.com/assets/1/a/7/9/9/Sensirion_CO2_Sensors_SCD30_Preliminary-Datasheet.pdf) - Drawing in the PDF at the end.
![image](https://user-images.githubusercontent.com/2559382/128624018-997eb5e1-9cfd-490a-b95d-b011379cec3f.png)
* [GPS](https://www.amazon.com/gp/product/B07P8YMVNT/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1) - The GPS only has one hole weirdly, so maybe I should look for one with two holes haha. 
![image](https://user-images.githubusercontent.com/2559382/128623980-116d2f44-70bc-4ebb-9f45-89ea22be4888.png)
* [Barometer]
![image](https://user-images.githubusercontent.com/2559382/128623993-dd12bc24-d5d2-4b37-8ba6-38179d45433b.png)

**Comment by eaudiffred** [comment]
Here is an updated draft based on the dimensions.

- The pi, barometer, and GPS sit on the front.  The sensor sits on the back.  
- I had to guess on the hole location for the sensor though.  It looks like its attached to a board that isn't show in the PDF for some reason. 
- The GPS attachment (idk what that part is called) doesn't have mount points, so how about clipping it in place?  I've tried this before with other 3D printed parts and have had some success and some failures.  
- I also made the entire footprint bigger, based on the internal dimensions of that housing.  

Let me know what you think.

![image](https://user-images.githubusercontent.com/88562047/128741889-560ba0e9-98f4-482e-81df-3bd79dbf9333.png)
![image](https://user-images.githubusercontent.com/88562047/128741950-7569e654-e7e6-4a35-a8e6-302b15310142.png)
![image](https://user-images.githubusercontent.com/88562047/128741994-200cd644-ef52-475c-9e0c-3416819c497c.png)
![image](https://user-images.githubusercontent.com/88562047/128742725-c0a82dc3-a775-4ffc-bde2-f95994dd47ff.png)
![image](https://user-images.githubusercontent.com/88562047/128742762-f0c8b8ed-090d-44db-a65c-9ebc30574f35.png)

**Comment by keenanjohnson** [comment]
Wow @eaudiffred this is incredible! Thanks! Great idea for the clip! Do you have an stl file or a link to the cad source so I can try to print a test version?

**Comment by keenanjohnson** [comment]
And yes there is a carrier board for the scd30 sensor that I should have linked to instead of the sensor board. Here are the dimensions for that :)

![72F6B381-B653-4FE4-A7BA-5CEA312D9972](https://user-images.githubusercontent.com/2559382/128749028-ef1cd6f9-0c6e-4e66-b160-2dbba66cdc7a.jpeg)


https://cdn-learn.adafruit.com/downloads/pdf/adafruit-scd30.pdf?timestamp=1628525130

**Comment by eaudiffred** [comment]
Do you have a measurement for the GPS attachment?  I guessed at that dimension too.  I'll update those and get you a file.

**Comment by keenanjohnson** [comment]
The GPS antennae (Tan block in the picture) has these dimensions: 

L: 15 mm
W: 15 mm
H: 6 mm

You rock!

**Comment by eaudiffred** [comment]
Glad you like it!

The dimensions are exact right now, so after we see how the first print comes out I can adjust tolerances as needed.  

I'm a little worried about the attachment clip being too small to get a good print, or not quite flexible enough to snap into place, but I guess we will see what happens.  

![image](https://user-images.githubusercontent.com/88562047/128757609-c92fd6a3-e645-44ca-8875-15ac18ec2da1.png)
![image](https://user-images.githubusercontent.com/88562047/128757681-4a501de5-5f95-4367-9000-500695f9dc8d.png)
[Sensor Clip.zip](https://github.com/Ribbit-Network/ribbit-network-frog-sensor/files/6956688/Sensor.Clip.zip)

Let me know if that zip attachment opens.  I couldn't get the STL file to attach on here.

**Comment by keenanjohnson** [comment]
The stl file opened just fine for me! Starting a test print now. I had to split the file into two parts that I'll glue together  because I have a tiny printer for now. A bigger printer is coming later this week luckily.

Thanks again for all your help Eric! What cad tool are you using?

https://user-images.githubusercontent.com/2559382/128767674-1a27d177-6c4f-403e-b898-7f4aa5d9e9df.MOV

**Comment by eaudiffred** [comment]
Nice!  What's the bed size on the new one you have coming?

Right now I'm using Fusion 360 (you can get a free trial for one year).  I prefer SolidWorks, but it's pricy.  

This project is really a cool idea, and I love doing CAD design, so I'm happy to help!

**Comment by keenanjohnson** [comment]
I got an [Ender-3 V2 3D Printer](https://www.creality3dofficial.com/products/ender-3-v2-3d-printer) which can print 220 x 220 x 250mm. :)

**Comment by keenanjohnson** [comment]
Excellent news! I printed the first bracket and glued the two pieces together for a test assembly this morning! Overall this is excellent! The brass inserts I had worked perfectly in the holes provided and all the holes lined up correctly! Great work!

### Brass Inserts
![IMG_9204](https://user-images.githubusercontent.com/2559382/128920393-20f3a79a-5725-4287-a851-e1aa22dc6a40.JPG)

### Finished Assembly
![IMG_9212](https://user-images.githubusercontent.com/2559382/128920549-aadfafbd-73a6-4e28-9c1c-651ffaa64f67.JPG)

### Issues Encountered

I just ran into a few snags while putting it together that I think can be easily fixed :)

* The clip didn't actually fit in the slot at it's 100% of printing. I printed a 97% scale clip and that easily fit
* The GPS antennae that goes in the clip is actually a little taller than I thought. There is a little bump on the bottom that makes it about 8 mm tall instead of six, so the clip height will need to be increased for that
* As printed the wires had to wrap around the side of the bracket and were sorta rubbing on the enclosure as it was inserted in (see pictures below). Since the GPS clip didn't work, I was able to just route the cables through the GPS clip hole and that worked well. So we should probably add another hole for a cable pass-through. Then I just hot glued the clip on and it made a nice cable retainer actually haha
![IMG_9211](https://user-images.githubusercontent.com/2559382/128921212-72589c59-3f95-43e8-91e7-441ed07e885c.JPG)
![IMG_9207](https://user-images.githubusercontent.com/2559382/128921140-b247b376-e15a-487c-be34-1b38af764ce7.JPG)
* You'll also notice that the USB cable for the GPS sticks out quite a bit in the design orientation (see picture above) and definitely bonks the enclosure going in. I was actually able to just rotate it under the barometer above, see below and that worked out fine.
* ![IMG_9212](https://user-images.githubusercontent.com/2559382/128921556-18a55df0-45a4-4812-929b-e722b0dfac33.JPG)
* Finally, once everything is stacked up, there isn't much width clearance for the whole stack. I definitely knocked the sensor pretty hard getting it into the enclosure. I think this would be fixed if we just made the bracket less thick. Maybe down to like 5 mm or so would be fine
![IMG_9215](https://user-images.githubusercontent.com/2559382/128921818-8d4a495d-06bc-4843-a4be-19a1d06d6e92.JPG)
The widest point using 6mm long brass standoffs seems to be about 50 mm right now
![IMG_9216](https://user-images.githubusercontent.com/2559382/128922175-c291def3-8640-4a2d-87e6-9ba7b7e9f850.JPG)

**Comment by eaudiffred** [comment]
Great feedback.

What do you think about this modified layout?  More cable conscious.  

Also shrink the body width by 5mm.

![image](https://user-images.githubusercontent.com/88562047/128930529-0fec505a-7864-4735-8480-94eae5b8988d.png)

**Comment by keenanjohnson** [comment]
I like it!

**Comment by eaudiffred** [comment]
Here are the new files.  
The thickness is now 5mm.  I adjusted the dimensions of the clip too.  I think it will work without scaling.  

[Sensor Clip v24.zip](https://github.com/Ribbit-Network/ribbit-network-frog-sensor/files/6964865/Sensor.Clip.v24.zip)

**Comment by keenanjohnson** [comment]
You are the best! I'll start this printing now and report back when it's
done!

**Comment by keenanjohnson** [comment]
@eaudiffred great news! In the past few days, I've successfully set up the new printer and I've successfully printed a few of the brackets above. Great work!

However, I've run into a supply chain issue where I could actually procure more than just a few of the Raspberry Pi Zero we were using in the design above. Given that, I made the decision to switch to a different board and I've updated the BOM accordingly [here](https://docs.google.com/spreadsheets/d/1lsWCXFawsJNGc44bqFXWkpjHfIFZQEj5UceJV4AiuK0/edit#gid=0)

Unfortunately, that board is quite a bit bigger and the bracket needed to be redesigned. I was impatient and you're doing more interesting work on the enclosure itself, so I went ahead and did the modeling.

I used OnShape, since it's free for public files and therefore lends itself well to Open Source like this, though maybe it's not really the best long term CAD tool. [The OnShape design is here for everyone to check out](https://cad.onshape.com/documents/0346e0daf22b10d5611dbc95/w/a8aaa87c5f1f082117b56412/e/c0f8f27ffabd2dd2476885f1).

I made a few other changes to our design and I feel good about this. I'm going to assemble one tomorrow and then close out this task if there aren't any issues found. Check out the CAD images below

Changes:
- Updated the main compute to the Raspberry Pi 4 CM + a Waveshare baseboard
- Added an antennae for the raspberry pi to increase the wifi connection range ( This will really help based on my testing)
- Increased the thickness to 7 mm so it clicks into the enclosure more securely
- Added a handle to the bottom of the bracket which makes it way easier to pull out of the enclosure locking mechanism
- I added an additional cable passthrough given the relocation of the modules

## Front
![image](https://user-images.githubusercontent.com/2559382/129686982-99f6c7c8-e232-4d93-a577-0efba911ea6f.png)

## Back
![image](https://user-images.githubusercontent.com/2559382/129687204-3ccaed34-c597-4134-84ec-ec6f7ce9edae.png)

## Side Profile
![image](https://user-images.githubusercontent.com/2559382/129687586-cc7f4206-9b9f-4637-82c8-02185ed24f9b.png)

**Comment by eaudiffred** [comment]
Glad you got the printer up and running!  The changes look great, everything fits on there nicely.  Great idea modeling the electrical components too!  Post some pictures when you have it printed and assembled.  

I'll check out OnShape.

**Comment by keenanjohnson** [comment]
Awesome! I built one today after a few revisions yesterday and I'll post pictures shortly.

Let me know what you think about OnShape. You're more of the expert on which tool is correct than me, I just know the basics of OnShape and I like that it's free to use for OpenSource, but if it's the wrong tool for the job (vs Fusion 360 ) we can definitely switch :)

**Comment by eaudiffred** [comment]
I like On Shape.  Its really nice for being free software.  I've only made that housing so far, but its user friendly, intuitive, and has a multitude of functionality that I think a lot of the free stuff often lacks.  I'm on board with using it.  The file and navigation structure is great too once you get used to it.

**Comment by keenanjohnson** [comment]
This bracket came together super well! I might make a few minor adjustments for cable routing but then I'm going to call this done I think for this version. 

![image](https://user-images.githubusercontent.com/2559382/130154144-374224b0-885c-4ce4-b87a-95f5afbd5e36.jpeg)

![image](https://user-images.githubusercontent.com/2559382/130154157-7d2cc80d-aa31-4599-8712-72702c53a0f3.jpeg)

**Comment by eaudiffred** [comment]
Looks great!  Efficient use of space.  

Is the GPS antennae glued into that hole/does the clip work?  If it's not working I'll try to think of a different mounting method.

**Comment by keenanjohnson** [comment]
Haha oh yeah good reminder. I actually just stuck it in there temporarily while the clip was printing but I should pull it out of there and try the clip. Orienting it in that orientation is better for the GPS antennae reception, [so in my current CAD](https://cad.onshape.com/documents/0346e0daf22b10d5611dbc95/w/a8aaa87c5f1f082117b56412/e/c0f8f27ffabd2dd2476885f1), I changed the clip dimensions to still use the clip, but keep it in that axis. I'll report back if that works haha.

**Comment by keenanjohnson** [comment]
Here's the bracket with the clip installed. It seems to work well. 

![image](https://user-images.githubusercontent.com/2559382/130296378-cc209f8e-1aa8-4dd3-bdb4-a15951e64a51.jpeg)

![image](https://user-images.githubusercontent.com/2559382/130296407-8f041e3b-4c7b-406b-a1b7-153aa5a12fa1.jpeg)

![image](https://user-images.githubusercontent.com/2559382/130296417-1091b48d-5bff-4200-9408-cceb7e6e94b0.jpeg)

I noticed that if the gps antennae cable is touching the usb cable, the gps will fail to get a gps lock indicating that the usb cable is fairly RF noisy. I probably need to add some little feature to retain the cables apart from each other.

**Comment by keenanjohnson** [comment]
Ok I've made a few minor tweaks to this original bracket and I'm printing one to test now. The biggest change is I've also added some sidewalls to help protect the sensors from getting bumped against the interior ribs of the enclosure when you take it in and out. I also made some slight adjustments in placing of things to help with cable routing.

![image](https://user-images.githubusercontent.com/2559382/130305885-23390f38-4172-4ec2-bd88-e3b1a37488c8.png)

[Onshape File](https://cad.onshape.com/documents/0346e0daf22b10d5611dbc95/w/a8aaa87c5f1f082117b56412/e/c0f8f27ffabd2dd2476885f1)

I released this as V1 of the bracket in OnShape.

**Comment by eaudiffred** [comment]
I like it.  Have you had a chance to print it?

**Comment by keenanjohnson** [comment]
Indeed! I assembled the first one today and it looks great! ![image](https://user-images.githubusercontent.com/2559382/130575334-dcdcf4d7-71ce-4c1b-b0fc-906583b29fad.jpeg)

![image](https://user-images.githubusercontent.com/2559382/130575356-b7f45c3e-5530-48a9-8ee4-add07d5cf988.jpeg)

**Comment by keenanjohnson** [comment]
This looks good to me, so I'm going to close this ticket out as complete for this version of the sensor.
