### ISSUE TITLE
step "insert the SD card on the slot of the carrier board" is missing in the assembly instructions.

### ISSUE THREAD

**Issue by pascaljoly** [Ribbit-Network/ribbit-network-frog-sensor#160]
https://github.com/Ribbit-Network/ribbit-network-frog-sensor/blob/main/hardware/v3/assembly-instructions/4-assembly.md

**Comment by eaudiffred** [comment]
Opened PR #177  to add this detail.

@pascaljoly, I added this to the software instructions.

**Comment by pascaljoly** [comment]
thanks. I would add it to the hardware instructions instead. In the software instructions, point to the hardware instructions with a link.
