### ISSUE TITLE
Document Sensor Assembly

### ISSUE THREAD

**Issue by eren-rudy** [Ribbit-Network/ribbit-network-frog-sensor#21]
Goal is to get a working sensor system up and running, documenting the process to catch potential issues along the way and make the process easier in the future.

**Comment by keenanjohnson** [comment]
Hey @eren-rudy this is the next thing on the todo list before Alpha test units are ready to ship, so I'm going to knock out a first draft today. I would appreciate a review though :)

**Comment by keenanjohnson** [comment]
I believe I have completed a first draft of all the assembly instructions. 

https://github.com/Ribbit-Network/ribbit-network-frog-sensor/blob/main/assembly-instructions/0-start-here.md
