### ISSUE TITLE
Create document for CO2 sensor research

### ISSUE THREAD

**Issue by eren-rudy** [Ribbit-Network/ribbit-network-frog-sensor#26]
The current CO2 sensor has potentially limited calibration capabilities (See #23). This may also apply to other similar sensors, but it is worth documenting other options that may be viable. 

Going to start compiling some preliminary research in Google Sheets for now.

**Comment by keenanjohnson** [comment]
Thanks @eren-rudy ! You rock!

**Comment by eren-rudy** [comment]
Linked Google Sheet in the CO2-Senor-Selection.md file in the wiki.
