### ISSUE TITLE
Measure the Power Consumption of the Frog Sensor

### ISSUE THREAD

**Issue by keenanjohnson** [Ribbit-Network/ribbit-network-frog-sensor#4]
The power consumption of the frog sensor should be measured for future projects and to reasonably estimate the power emissions produced by this device.

**Comment by eaudiffred** [comment]
Are you wanting to add hardware to each unit and have the power consumption reported with the air quality data?  Or just set up a test with one of them to get an estimate?

This [INA219 board](https://www.adafruit.com/product/904) looks like it could be added to each unit to measure real time power consumption.  Connecting it seems easy, but idk how you get the data, I'm out of my league there.  [(video)
](https://www.youtube.com/watch?v=BgShCD7xT_A)
If its just a test on one unit, can you sacrifice a power cord and use a multimeter?

**Comment by keenanjohnson** [comment]
I just wanted to test one of them at first to get a rough estimate for emissions calculations. 

Yeah I just received an outlet power meter today so I'll run that test shortly. In the future, we'll definitely include onboard power monitoring as build out a solar-powered version of the Frog.

**Comment by keenanjohnson** [comment]
See the Solar Powered Project for more tasks outstanding there :)

https://github.com/Ribbit-Network/ribbit-network-frog-sensor/projects/2

**Comment by keenanjohnson** [comment]
It looks like the sensor is using about 2.6 Watts of power.
